/**:
    ros__parameters:
        image_transport: raw    # image format
        family: 36h11           # tag family name
        size: 0.055             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 2          # number of threads
            decimate: 1.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.5    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory

        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # optional list of tags
        tag:
            ids: [6, 7, 3, 1, 2, 8 ,4]            # tag ID
            frames: [phone, button, mouse, banana, kindle, keys, socks]  # optional frame name